# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure jitsi-prosody paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0777"
    owner: "{{ jitsi_uid }}"
    group: "{{ jitsi_gid }}"
  with_items:
    - "{{ jitsi_prosody_base_path }}"
    - "{{ jitsi_prosody_config_path }}"
    - "{{ jitsi_prosody_plugins_path }}"
    - "{{ jitsi_prosody_ext_path }}"

- name: Ensure jitsi-prosody support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/prosody/{{ item }}.j2"
    dest: "{{ jitsi_prosody_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ jitsi_uid }}"
    group: "{{ jitsi_gid }}"
  with_items:
    - env
    - labels

- name: Ensure jitsi-prosody container image is pulled via community.docker.docker_image
  when: devture_systemd_docker_base_container_image_pull_method == 'ansible-module'
  community.docker.docker_image:
    name: "{{ jitsi_prosody_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ jitsi_prosody_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else jitsi_prosody_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure jitsi-prosody container image is pulled via ansible.builtin.command
  when: devture_systemd_docker_base_container_image_pull_method == 'command'
  ansible.builtin.command:
    cmd: "{{ devture_systemd_docker_base_host_command_docker }} pull {{ jitsi_prosody_container_image }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed
  changed_when: "'Downloaded newer image' in result.stdout"

# Configure Matrix authentication.
- name: Install Prosody Auth Matrix User Verification plugin
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/util/setup_jitsi_auth_uvs_install.yml"
  when: jitsi_enable_auth | bool and jitsi_auth_type == "matrix"

# Remove Matrix authentication if disabled
- name: Ensure Prosody Auth Matrix User Verification plugin is not present if Matrix auth is disabled
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/util/setup_jitsi_auth_uvs_uninstall.yml"
  when: (not jitsi_enable_auth | bool) or (jitsi_auth_type != "matrix")

- name: Ensure jitsi-prosody systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/prosody/systemd/prosody.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ jitsi_identifier }}-prosody.service"
    mode: "0644"
  register: jitsi_prosody_systemd_service_result

# Tasks that require a running Prosody container are called in this file.
- name: Run Prosody related tasks, that require a running container
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/util/setup_jitsi_prosody_post_setup_hooks.yml"
  when:
    - jitsi_enable_auth | bool and jitsi_auth_type == "internal"
